name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure build dir exists
        run: mkdir -p build

      - name: Copy images directory (if exists)
        run: if [[ -d img ]]; then cp -R img build/img; fi
        
      - name: Converts README.md to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: build/index.html
          dark-mode: false
          markdown-style-theme: dark
          github-corners: https://github.com/DSSS-Lab/survey_al21022_toma

      - name: replace .md to .html
        run: sed -i 's/\.md/\.html/g' build/index.html

      - name: Check if docs folder exists
        id: docs-folder-exists
        run: bash -c "[[ -d docs ]] ; echo \"has_docs=\$?\" >> \"$GITHUB_OUTPUT\""

      - name: Marp Build (docs folder, if exists)
        if: steps.docs-folder-exists.outputs.has_docs == '0'
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: --html -I docs/ -o build/docs/
        env:
          MARP_USER: root:root

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
